name : Dane Clark Collins
brand : Dane Clark Collins
description : Writer & Musician
keyword:
url : http://www.daneclarkcollins.com/
imageurl: http://www.daigo.org/wordpress/wp-content/themes/daigo_org-theme-2013/img/glasses.png
email : dane@daneclarkcollins.com
twitter : dane_collins
author: Dane Clark Collins
analytics:
year: 2014
markdown: kramdown
