name : Dane Clark Collins
brand : Dane Clark Collins
description : Writer & Musician
url : http://daneclarkcollins.github.io/daneclarkcollins-com
author: Dane Clark Collins
twitter: dane_collins
analytics:
year: 2014
markdown: kramdown
permalink: /blog/:title
paginate: 10
paginate_path: "/blog/page:num"
